# Generated by Django 4.2.7 on 2023-11-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.CharField(max_length=2000, verbose_name='краткая биография')),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('releaseyear', models.SmallIntegerField()),
                ('developer', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('cover', models.ImageField(blank=True, upload_to='myapp/static/covers/')),
                ('description', models.CharField(max_length=2000, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='жанр')),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='должность')),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='myapp/static/screens/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.game')),
            ],
        ),
        migrations.CreateModel(
            name='gameseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.game')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.series')),
            ],
        ),
        migrations.CreateModel(
            name='gamecreators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.creator')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.game')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.role')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='creators',
            field=models.ManyToManyField(through='gdb.gamecreators', to='gdb.creator'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='gdb.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='gdb.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ManyToManyField(through='gdb.gameseries', to='gdb.series'),
        ),
        migrations.CreateModel(
            name='alt_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdb.game')),
            ],
        ),
    ]
