# Generated by Django 4.2.7 on 2023-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_games_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='games',
        ),
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.ManyToManyField(to='myapp.genres'),
        ),
    ]
